"""add experience_level and tech_stack to jobs

Revision ID: 6cdcceae8480
Revises: 244c45b40172
Create Date: 2026-07-19 12:23:37.741552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cdcceae8480'
down_revision: Union[str, None] = '244c45b40172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('jobs', sa.Column('experience_level', sa.String(length=50), nullable=True))
    # server_default is required here (not just the Python-level
    # `default=list` on the ORM model) -- that Python default only
    # applies to NEW rows inserted through SQLAlchemy going forward.
    # This ALTER TABLE runs against a table that may already have
    # existing rows (it does, in any real deployment past the first
    # migration), and Postgres needs a value to backfill those existing
    # rows with in order to satisfy NOT NULL. Discovered by actually
    # running this migration against a populated table, not by reading
    # the autogenerated diff.
    op.add_column(
        'jobs',
        sa.Column(
            'tech_stack',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )


def downgrade() -> None:
    op.drop_column('jobs', 'tech_stack')
    op.drop_column('jobs', 'experience_level')
